[package]
name = "bin2dec"
version = "2.0.0"
authors = ["CNife <CNife@vip.qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.6"
num = "0.2.1"
